### ISSUE TITLE
Create API Documentation Using Swagger

### ISSUE THREAD

**Issue by habeshaethiopia** [maajidAwol/ConnectX#27]
### **Description**

We need to implement API documentation for our project using Swagger to improve clarity and usability for developers. This will provide a comprehensive reference for all API endpoints, including request/response formats, authentication mechanisms, and possible errors.

---

### **Tasks**

1. **Install Swagger Tools**  
   - Integrate `drf_yasg` for generating Swagger documentation.
   - Ensure dependencies are added to the project (e.g., `pip install drf-yasg`).

2. **Configure Swagger in the Project**  
   - Update `urls.py` to include Swagger endpoints:
     ```python
     from drf_yasg.views import get_schema_view
     from drf_yasg import openapi
     from rest_framework.permissions import AllowAny

     schema_view = get_schema_view(
         openapi.Info(
             title="API Documentation",
             default_version='v1',
             description="API documentation for the project",
             terms_of_service="https://www.google.com/policies/terms/",
             contact=openapi.Contact(email="contact@example.com"),
             license=openapi.License(name="BSD License"),
         ),
         public=True,
         permission_classes=(AllowAny,),
     )

     urlpatterns += [
         path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
         path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
     ]
     ```

3. **Document Endpoints**  
   - Use the `@swagger_auto_schema` decorator in views to document request/response schemas.
   - Ensure each endpoint includes details such as:
     - Parameters
     - Authentication requirements
     - Response status codes
     - Example payloads (where applicable)

4. **Support Authentication**  
   - Configure JWT (Bearer Token) authentication for the documentation in `settings.py`:
     ```python
     SWAGGER_SETTINGS = {
         'SECURITY_DEFINITIONS': {
             'Bearer': {
                 'type': 'apiKey',
                 'name': 'Authorization',
                 'in': 'header',
                 'description': 'JWT Authentication using Bearer scheme. Example: "Bearer {token}"',
             },
         },
         'USE_SESSION_AUTH': False,
     }
     ```

5. **Test the Documentation**  
   - Verify that all endpoints are listed and properly documented.
   - Ensure curl requests in Swagger UI work as expected.

---

### **Acceptance Criteria**

- [ ] Swagger UI (`/swagger/`) displays a clear and accurate list of all endpoints.
- [ ] Each endpoint includes detailed documentation (parameters, responses, etc.).
- [ ] Authentication is integrated into Swagger (JWT Bearer token support).
- [ ] API documentation updates automatically when new endpoints are added.

---

### **Additional Notes**

- Refer to the [[drf-yasg documentation](https://drf-yasg.readthedocs.io/)](https://drf-yasg.readthedocs.io/) for guidance on advanced configuration.
- Ensure that all developers are informed about how to add documentation for new endpoints.
